version: 2

jobs: 
  build:
    docker:
      - image: circleci/python:3.8-browsers
        environment:
          FLASK_APP: app
          FLASK_ENV: development

    steps:
      - checkout
      - run:
          command: mkdir test-reports

      - run:
          name: Install python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Start posting tweet unittest
          command: |
            . venv/bin/activate
            python -m unittest tests/tweet_test.py
      - store_artifacts:
          path: test-reports
          destination: tr1
      - store_test_results:
          path: test-reports

