version: 2

jobs: 
  build:
    docker:
      - image: circleci/python:3.8-browsers
        environment:
          FLASK_APP: app
          FLASK_ENV: development

    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          commadn: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - run:
          name: Install python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Start posting tweet unittest
          command: |
            . venv/bin/activate
            python -m unittest tests/tweet_test.py
      - store_artifacts:
          path: test-reports
          destination: tr1
      - store_test_results:
          path: test-reports

