"""add avatar_path & some changes in Tweet model

Revision ID: 03f00ed5912d
Revises: dba5835d21c3
Create Date: 2020-08-01 14:22:32.284065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f00ed5912d'
down_revision = 'dba5835d21c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('fav_count', sa.Integer(), nullable=True))
    op.add_column('tweet', sa.Column('text', sa.String(length=280), nullable=False))
    op.add_column('tweet', sa.Column('tweeted_at', sa.DateTime(), nullable=True))
    op.add_column('tweet', sa.Column('tweeted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['tweeted_by'], ['id'])
    op.add_column('user', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'tweeted_by')
    op.drop_column('tweet', 'tweeted_at')
    op.drop_column('tweet', 'text')
    op.drop_column('tweet', 'fav_count')
    # ### end Alembic commands ###
