"""add login_counr & avatar default path

Revision ID: 49df02d937fb
Revises: b15281aec229
Create Date: 2020-08-05 16:54:08.515150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49df02d937fb'
down_revision = 'b15281aec229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    # ### end Alembic commands ###
