"""change tweeted_at column

Revision ID: 52a844259036
Revises: 49df02d937fb
Create Date: 2020-08-11 17:41:56.001923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a844259036'
down_revision = '49df02d937fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'tweeted_at')
    op.add_column('tweet', sa.Column('tweeted_at', sa.String(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('tweet', 'tweeted_at')
    # ### end Alembic commands ###
