"""add liked_by_me column to like model

Revision ID: 874f1df99fbd
Revises: 52a844259036
Create Date: 2020-08-14 19:03:01.245461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874f1df99fbd'
down_revision = '52a844259036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('liked_by_me', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'liked_by_me')
    # ### end Alembic commands ###
