"""like model & some changes

Revision ID: b15281aec229
Revises: 03f00ed5912d
Create Date: 2020-08-02 19:03:13.331410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15281aec229'
down_revision = '03f00ed5912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tweet', 'fav_count')
    op.add_column('user', sa.Column('bio', sa.String(length=160), nullable=True))
    op.add_column('user', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    op.drop_column('user', 'bio')
    op.add_column('tweet', sa.Column('fav_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('like')
    # ### end Alembic commands ###
