"""retweet

Revision ID: cb49fbd52a45
Revises: 9f7bc7b1f771
Create Date: 2020-08-30 18:55:23.130809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb49fbd52a45'
down_revision = '9f7bc7b1f771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('is_retweet', sa.Boolean(), nullable=True))
    op.add_column('tweet', sa.Column('source_tweet_id', sa.Integer(), nullable=True))
    op.alter_column('tweet', 'text',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    op.create_foreign_key(None, 'tweet', 'tweet', ['source_tweet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.alter_column('tweet', 'text',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    op.drop_column('tweet', 'source_tweet_id')
    op.drop_column('tweet', 'is_retweet')
    # ### end Alembic commands ###
