"""add tweety prefix

Revision ID: f846f5c783e9
Revises: cb49fbd52a45
Create Date: 2020-09-07 19:49:07.702784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f846f5c783e9'
down_revision = 'cb49fbd52a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # rename all tables and add a `tweety` prefix
    op.rename_table('tweet', 'tweety__tweet')
    op.rename_table('user', 'tweety__user')
    op.rename_table('like', 'tweety__like')
    op.rename_table('bookmark', 'tweety__bookmark')
    op.rename_table('role', 'tweety__role')
    op.rename_table('roles_users', 'tweety__roles_users')
    op.rename_table('user_follow', 'tweety__user_follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # rename all tables and remove `tweety` prefix
    op.rename_table('tweety__bookmark', 'bookmark')
    op.rename_table('tweety__like', 'like')
    op.rename_table('tweety__role', 'role')
    op.rename_table('tweety__roles_users', 'roles_users')
    op.rename_table('tweety__tweet', 'tweet')
    op.rename_table('tweety__user_follow', 'user_follow')
    # ### end Alembic commands ###
